server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: bms-gateway
  cloud:
    gateway:
      routes:
      - id: blessmysouldbackend
        uri: lb://BLESSMYSOULBACKEND
        predicates:
        - Path=/api/v1/**
        
logging:
  level: 
    root: WARN
    org.springframework: WARN
